name: PlayerPing
main: bl4ckscor3.plugin.playerping.core.PlayerPing
version: 1.5.5
author: bl4ckscor3
description: Highlights the name of a player in the chat and plays a sound to them, if they are mentioned.
commands:
    playerping:
        description: Basic command of the plugin.
        usage: /<command> <toggle|reload|addAlias|add|removeAlias|remove|listAlias|list> [sound|highlight|aliasName]
        aliases: [pp]
permissions:
    playerping.*:
        description: Gives access to all PlayerPing commands.
        children:
            playerping.reload: true
            playerping.toggle.*: true
            playerping.toggle.highlight: true
            playerping.toggle.sound: true
            playerping.toggle.all: true
    playerping.toggle.*:
        description: Gives access to all toggle commands.
        children:
            playerping.toggle.highlight: true
            playerping.toggle.sound: true
            playerping.toggle.all: true
    playerping.reload:
        description: Gives permission to reload the configuration from ingame.
        default: op
    playerping.toggle.highlight:
        description: Gives permission to toggle chat highlighting on/off.
        default: op
    playerping.toggle.sound:
        description: Gives permission to toggle the sound on/off.
        default: op
    playerping.toggle.all:
        description: Gives permission to toggle highlighting AND sound onf/off.
        default: op
        